# Generated by Django 4.2.3 on 2023-07-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('time_of_bookmark', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_trailer', models.FileField(upload_to='trailer/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_width', models.CharField(editable=False, max_length=150, null=True)),
                ('video_height', models.CharField(editable=False, max_length=150, null=True)),
                ('duration', models.CharField(editable=False, max_length=150, null=True)),
                ('thumbnail_light', models.ImageField(blank=True, null=True, upload_to='thumbnails/thumbnails_light/')),
                ('thumbnail_dark', models.ImageField(blank=True, null=True, upload_to='thumbnails/thumbnails_dark/')),
                ('video_file', models.FileField(upload_to='')),
                ('video_file_2k', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_2k/')),
                ('video_file_fullhd', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_fullhd/')),
                ('video_file_hd', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_hd/')),
                ('video_file_480', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_480p/')),
                ('video_file_360', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_360p/')),
                ('video_file_240', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_240p/')),
                ('video_file_144', models.FileField(blank=True, null=True, upload_to='videos/mp4_resized_144p/')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bookmarks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.bookmark', verbose_name='Bookmarks')),
                ('category', models.ManyToManyField(to='videos.category')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.course', verbose_name='Course')),
                ('keywords', models.ManyToManyField(to='videos.keyword')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.section', verbose_name='Lesson Section')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.ManyToManyField(to='videos.keyword'),
        ),
    ]
