"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from typing import Optional
from gqlauth.settings_type import GqlAuthSettings, email_field, password_field, first_name_field, last_name_field
from gqlauth.settings_type import GqlAuthSettings
from strawberry.annotation import StrawberryAnnotation
from strawberry.field import StrawberryField

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'MY-DJANGO-KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "strawberry.django",
    "gqlauth",
    "videos",
    "users"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "gqlauth.core.middlewares.django_jwt_middleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False
# USE_L10N = True
USE_TZ = True

DATE_INPUT_FORMATS = ('%d/%m/%Y','%d-%m-%Y')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

profile_image_field = StrawberryField(
    python_name="profile_image",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)
date_of_birth_field = StrawberryField(
    python_name="date_of_birth",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)
phone_field = StrawberryField(
    python_name="phone",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)
country_field = StrawberryField(
    python_name="country",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)
city_field = StrawberryField(
    python_name="city",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)
zip_code_field = StrawberryField(
    python_name="zip_code",
    default=None,
    type_annotation=StrawberryAnnotation(Optional[str]),
)

GQL_AUTH = GqlAuthSettings(
    SEND_ACTIVATION_EMAIL=True,
    LOGIN_REQUIRE_CAPTCHA=False,
    REGISTER_REQUIRE_CAPTCHA=False,
    ALLOW_LOGIN_NOT_VERIFIED=False,
    # JWT_PAYLOAD_PK=field(default_factory=lambda: email_field),
    LOGIN_FIELDS=set([email_field, password_field]),
    # ACTIVATION_PATH_ON_EMAIL="confirm",
    REGISTER_MUTATION_FIELDS=set([email_field, first_name_field, last_name_field, date_of_birth_field, phone_field, country_field, city_field, zip_code_field]),
    UPDATE_MUTATION_FIELDS=set([first_name_field, last_name_field, phone_field, country_field, city_field, zip_code_field]),
    EMAIL_TEMPLATE_VARIABLES={
        'site_name': 'Real Trading 23',
        'protocol': 'http',
        'frontend_domain': 'localhost:3000',
        'path': 'user/verify',
        'path2': 'user/reset-password',
    }
)

AUTH_USER_MODEL = 'users.CustomUser'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://backend:8000"
]

CORS_ALLOW_CREDENTIALS = True